-- AlterTable
ALTER TABLE `News` ADD COLUMN `updateDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `Product` ADD COLUMN `updateDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
